#!/bin/bash
## START LIBRARY BUNDLE ##
_get_cursor_row() {
    local IFS=';'
    read -sdR -p $'\E[6n' ROW COL
    echo "${ROW#*[}"
}
_cursor_blink_on() { echo -en "\033[?25h" >&2; }
_cursor_blink_off() { echo -en "\033[?25l" >&2; }
_cursor_to() { echo -en "\033[$1;$2H" >&2; }
_key_input() {
    local ESC=$'\033'
    local IFS=''
    read -rsn1 a
    if [[ "$ESC" == "$a" ]]; then
        read -rsn2 b
    fi
    local input="${a}${b}"
    case "$input" in
        "$ESC[A") echo up ;;
        "$ESC[B") echo down ;;
        "$ESC[C") echo right ;;
        "$ESC[D") echo left ;;
        '') echo enter ;;
        ' ') echo space ;;
    esac
}
_new_line_foreach_item() {
    count=0
    while [[ $count -lt $1  ]]; do
        echo "" >&2
        ((count++))
    done
}
_prompt_text() {
    echo -en "\033[32m?\033[0m\033[1m ${1}\033[0m " >&2
}
_decrement_selected() {
    local selected=$1
    ((selected--))
    if [ "${selected}" -lt 0 ]; then
        selected=$(($2 - 1))
    fi
    echo -n $selected
}
_increment_selected() {
    local selected=$1
    ((selected++))
    if [ "${selected}" -ge "${opts_count}" ]; then
        selected=0
    fi
    echo -n $selected
}
input() {
    _prompt_text "$1"
                       echo -en "\e[36m\c" >&2
    read -r text
    echo -n "${text}"
}
confirm() {
    _prompt_text "$1 (y/N)"
    echo -en "\033[36m\c " >&2
    local result=""
    echo -n " " >&2
    until [[ "$result" == "y" ]] || [[ "$result" == "n" ]] || [[ "$result" == "Y" ]] || [[ "$result" == "N" ]]; do
        echo -e "\033[1D\c " >&2
        read -n1 result
    done
    echo -en "\033[0m" >&2
    case "$result" in
        y | Y) echo -n 1 ;;
        n | N) echo -n 0 ;;
    esac
    echo "" >&2
}
list() {
    _prompt_text "$1 "
    local opts=("${@:2}")
    local opts_count=$(($# - 1))
    _new_line_foreach_item "${#opts[@]}"
    local lastrow
                   lastrow=$(_get_cursor_row)
    local startrow
                    startrow=$((lastrow - opts_count + 1))
    trap "_cursor_blink_on; stty echo; exit" 2
    _cursor_blink_off
    local selected=0
    while true; do
        local idx=0
        for opt in "${opts[@]}"; do
            _cursor_to $((startrow + idx))
            if [ $idx -eq $selected ]; then
                printf "\033[0m\033[36m❯\033[0m \033[36m%s\033[0m" "$opt" >&2
            else
                printf "  %s" "$opt" >&2
            fi
            ((idx++))
        done
        case $(_key_input) in
            enter) break  ;;
            up) selected=$(_decrement_selected "${selected}" "${opts_count}")  ;;
            down) selected=$(_increment_selected "${selected}" "${opts_count}")  ;;
        esac
    done
    echo -en "\n" >&2
    _cursor_to "${lastrow}"
    _cursor_blink_on
    echo -n "${selected}"
}
checkbox() {
    _prompt_text "$1"
    local opts
                opts=("${@:2}")
    local opts_count
                      opts_count=$(($# - 1))
    _new_line_foreach_item "${#opts[@]}"
    local lastrow
                   lastrow=$(_get_cursor_row)
    local startrow
                    startrow=$((lastrow - opts_count + 1))
    trap "_cursor_blink_on; stty echo; exit" 2
    _cursor_blink_off
    local selected=0
    local checked=()
    while true; do
        local idx=0
        for opt in "${opts[@]}"; do
            _cursor_to $((startrow + idx))
            local icon="◯"
            for item in "${checked[@]}"; do
                if [ "$item" == "$idx" ]; then
                    icon="◉"
                    break
                fi
            done
            if [ $idx -eq $selected ]; then
                printf "%s \e[0m\e[36m❯\e[0m \e[36m%-50s\e[0m" "$icon" "$opt" >&2
            else
                printf "%s   %-50s" "$icon" "$opt" >&2
            fi
            ((idx++))
        done
        case $(_key_input) in
            enter) break ;;
            space)
                local found=0
                for item in "${checked[@]}"; do
                    if [ "$item" == "$selected" ]; then
                        found=1
                        break
                fi
            done
                if [ $found -eq 1 ]; then
                    checked=("${checked[@]/$selected/}")
            else
                    checked+=("${selected}")
            fi
                ;;
            up) selected=$(_decrement_selected "${selected}" "${opts_count}")  ;;
            down) selected=$(_increment_selected "${selected}" "${opts_count}")  ;;
        esac
    done
    _cursor_to "${lastrow}"
    _cursor_blink_on
    IFS="" echo -n "${checked[@]}"
}
password() {
    _prompt_text "$1"
    echo -en "\033[36m" >&2
    local password=''
    local IFS=
    while read -r -s -n1 char; do
        [[ -z "${char}" ]] && {
                                printf '\n' >&2
                                                 break
        }
        if [ "${char}" == $'\x7f' ]; then
            if [ "${#password}" -gt 0 ]; then
                password="${password%?}"
                echo -en '\b \b' >&2
            fi
        else
            password+=$char
            echo -en '*' >&2
        fi
    done
    echo -en "\e[0m" >&2
    echo -n "${password}"
}
editor() {
    tmpfile=$(mktemp)
    _prompt_text "$1"
    echo "" >&2
    "${EDITOR:-vi}" "${tmpfile}" >/dev/tty
    echo -en "\033[36m" >&2
    cat "${tmpfile}" | sed -e 's/^/  /' >&2
    echo -en "\033[0m" >&2
    cat "${tmpfile}"
}
with_validate() {
    while true; do
        local val
                   val="$(eval "$1")"
        if ($2 "$val" >/dev/null); then
            echo "$val"
            break
        else
            show_error "$($2 "$val")"
        fi
    done
}
validate_present() {
    if [ "$1" != "" ]; then return 0; else
                                           echo "Please specify the value"
                                                                            return 1
    fi
}
show_error() {
    echo -e "\033[91;1m✘ $1\033[0m" >&2
}
show_success() {
    echo -e "\033[92;1m✔ $1\033[0m" >&2
}
LOG_ERROR=3
LOG_WARN=2
LOG_INFO=1
LOG_DEBUG=0
parse_log_level() {
    local level="$1"
    local parsed
    case "${level}" in
      info | INFO)   parsed=$LOG_INFO  ;;
      debug | DEBUG) parsed=$LOG_DEBUG  ;;
      warn | WARN)   parsed=$LOG_WARN  ;;
      error | ERROR) parsed=$LOG_ERROR  ;;
      *)             parsed=-1  ;;
    esac
    export LOG_LEVEL="${parsed}"
}
log() {
    local level="$1"
    local message="$2"
    local color=""
    if [[ $level -lt ${LOG_LEVEL:-$LOG_INFO} ]]; then
        return
    fi
    case "${level}" in
      "$LOG_INFO")
        level="INFO"
        color='\033[1;36m'
        ;;
      "$LOG_DEBUG")
        level="DEBUG"
        color='\033[1;34m'
        ;;
      "$LOG_WARN")
        level="WARN"
        color='\033[0;33m'
        ;;
      "$LOG_ERROR")
        level="ERROR"
        color='\033[0;31m'
        ;;
    esac
    echo -e "[${color}$(printf '%-5s' "${level}")\033[0m] \033[1;35m$(date +'%Y-%m-%dT%H:%M:%S')\033[0m ${message}"
}
detect_os() {
    case "$OSTYPE" in
        solaris*) echo "solaris"  ;;
        darwin*)  echo "macos"  ;;
        linux*)   echo "linux"  ;;
        bsd*)     echo "bsd"  ;;
        msys*)    echo "windows"  ;;
        cygwin*)  echo "windows"  ;;
        *)        echo "unknown"  ;;
    esac
}
get_opener() {
    local cmd
    case "$(detect_os)" in
        darwin)  cmd="open"  ;;
        linux)   cmd="xdg-open"  ;;
        windows) cmd="start"  ;;
        *)       cmd=""  ;;
    esac
    echo "$cmd"
}
open_link() {
    cmd="$(get_opener)"
    if [ "$cmd" == "" ]; then
        echo "Your platform is not supported for opening links."
        echo "Please open the following URL in your preferred browser:"
        echo " ${1}"
        return 1
    fi
    $cmd "$1"
    if [[ $? -eq 1 ]]; then
        echo "Failed to open your browser."
        echo "Please open the following URL in your browser:"
        echo "${1}"
        return 1
    fi
    return 0
}
## STOP LIBRARY BUNDLE ##
set -e
if ! command gpg --version > /dev/null
then
	show_error "No GPG installation found.\n\
For more details on installation please check https://github.com/timo-reymann/gpg-key-creation-assistant/tree/main#how-to-install-gpg\
After successfull installation you can run this script again."
    exit 2
else
	show_success "Found GPG '$(gpg --version | head -n1)'"
fi

# Full name
validate_name() {
    if [ "${#1}" -lt 3 ]; then echo "Please provide at least 3 letters"; return 1; fi
    if [[ ! "$1" =~ " " ]]; then echo "Your first and last name must be delimited by space"; return 1; fi
}
full_name=$(with_validate 'input "Your first and last name seperated by space. If you have multiple names you can use them as well"' validate_name)

# Email
validate_email() {
    if [ "${#1}" -lt 4 ] ; then echo "Please provide a email address at least contains the user and domain part"; return 1;fi
    if ! [[ "${1}" =~ ^.{1,}@.{1,}$  ]]; then echo "Please provide an email address containg at least a host and user part"; return 1; fi
}
email=$(with_validate 'input "E-Mail address that the key will be associated with"' validate_email)

# Passphrase
validate_passphrase() {
    if [ "${#1}" -lt 8 ]; then echo "Passphrase needs to be at least 5 characters"; return 1; fi
}
passphrase=$(with_validate 'password "Please enter a passphrase for your GPG key, that will be required import/export the key"' validate_passphrase)

# Key size in bit
key_sizes=("4096 (high)" "2048 (medium)" "1024 (low)")
key_size=$(list "Bit size of your key, the more bytes you choose the longer it takes for GPG to perform operations, increasing security as well" "${key_sizes[@]}")
case $key_size in
    0) bit_size=4096; ;;
    1) bit_size=2048; ;;
    2) bit_size=1024; ;;
esac

# Expiration
expire=$(confirm "Should the key expire after 1 year?")
if [ "$expire" = "0"  ]; then
    expires_in=0
else
    expires_in=365
fi

spec=$(mktemp)
cat >"$spec" <<EOF
     %echo Generating your GPG key
     Key-Type: RSA
     Key-Length: ${bit_size}
     Subkey-Type: RSA
     Subkey-Length: ${bit_size}
     Name-Real: ${full_name}
     Name-Email: ${email}
     Expire-Date: ${expires_in}
     Passphrase: ${passphrase}
     %commit
     %echo Key generated
EOF
gpg --batch --generate-key --no-tty -q $spec
rm $spec

# get private keys
secret_keys_formatted=()
secret_keys_raw=()
for line in $(gpg --list-secret-keys --with-colons --fingerprint "${email}"); do
    IFS=":" read -a fields <<<"$line"

    # set fields required based on type
    case ${fields[0]} in
        sec)
            key="${fields[4]}";
            bits="${fields[2]}";
            ;;
        uid)
            created_hours="$(((${fields[5]} - $(date +%s) / 360)))";
            ;;
    esac

    # ssb is the last entry per key we care about
    if [[ "${key}" != "${fields[4]}" ]] && [[ "${fields[0]}" == "ssb" ]]; then
        secret_keys_formatted+=("${key} (created $created_hours hours ago), ${bits} bit)")
        secret_keys_raw+=("${key}")
    fi
done

if [[ ${#secret_keys_raw[@]} -gt 1 ]]; then
    key_for_export_id=$(list "There were multiple keys found, please choose the one you want to use" "${secret_keys_formatted[@]}")
    key_for_export=${secret_keys_raw[${key_for_export_id}]}
else
    key_for_export=${secret_keys_raw[0]}
fi

show_success "Key to be set up: ${key_for_export}"

rm public.gpg || true >/dev/null
gpg --output public.gpg --armor --export "${key_for_export}"
show_success "Exported public key to '${PWD}/public.gpg'\n\
You can savely share this key with the world."

rm private.gpg || true >/dev/null
gpg --output private.gpg --armor --pinentry-mode loopback --passphrase "${passphrase}" --export-secret-key "${key_for_export}"
show_success "Exported private key to '${PWD}/private.gpg'\n\
Store it somewhere safe as a backup."

setup_git=$(confirm "Do you want to set up git to sign your commits?")
if [ "$setup_git" == "1" ]; then
    git config --global user.signingkey "${key_for_export}"
    git config --global commit.gpgsign true
    show_success "Git is now set up to autosign your commits"
    cat <<EOF
To make sure that the git hosters you are using now about your gpg key check the according documentations:
  - GitHub: https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
  - GitLab: https://docs.gitlab.com/ee/user/project/repository/gpg_signed_commits/#add-a-gpg-key-to-your-account

Public key to copy&paste:
EOF
    echo -en "\e[1b\e[37m\e[3m"
    while read -r line; do
        echo "${line}"
    done < public.gpg
    echo -en "\e[0m"

    if command -v gh --version >/dev/null; then
        show_success "GitHub CLI found, trying to publish key to GitHub"
        gh gpg-key add public.gpg || show_error "Failed to publish key, you can try to add it manually. Follow the doc link above to do that."
    fi
fi

